dbt_transform:
  outputs:
    dev:
      dbname: postgres
      host: warehouse-db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
