source:
  database: 'postgres'
  user: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: '5433'
  model: 'fct__german_credit_wide'

models:
  log-regression:
    columns:
      - 'risk'
      - 'sex'
      - 'credit_exposure'
      - 'loan_term_tier'
      - 'savings_score'
      - 'checking_score'
      - 'has_no_savings_info'
      - 'has_no_checking_info'
      - 'job_skill_level'
      - 'housing_stability_score'
      - 'purpose_risk_group'
    scale:
      - 'credit_exposure'
      - 'savings_score'
      - 'checking_score'
      - 'job_skill_level'
      - 'housing_stability_score'
    one-hot-encode:
      - 'sex'
      - 'loan_term_tier'
      - 'purpose_risk_group'
    target: 'risk'
    threshold: 0.53
  decision-tree:
    scale:
      - column1
      - column2
      - column3
      - column4
      - etc
    one-hot-encode:
      - column1
      - column2
      - column3
      - column4
      - etc
    target: 'risk'
